security:
    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        Star\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        
        fos_userbundle:
            id: fos_user.user_provider.username 

    firewalls:
        
        admin:
            pattern:            /admin(.*)
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                check_path:     /admin/login_check
                default_target_path: /admin/
            logout:
                path:           /admin/logout
                target:         /admin/login
            anonymous:    true

        #main:
        #    pattern: ^/
        #    form_login:
        #        provider: fos_userbundle
        #        csrf_provider: form.csrf_provider
        #    logout:       true
        #    anonymous:    true

        main:
            pattern: ^/.*
            anonymous: true
            provider: fos_userbundle
            form_login:
                check_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: espace_membre
            logout:
                path: fos_user_security_logout
                target: /
            remember_me:
                key: %secret%
            anonymous: true
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/deposer_annonce, role: ROLE_USER}
        - { path: ^/list-fav-user$, role: ROLE_USER}
        
        - { path: ^/admin/, role: ROLE_ADMIN }
