parameters:
#    star_user.example.class: Star\UserBundle\Example

services:
#    star_user.example:
#        class: %star_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
