<?php

namespace Star\AnnoncesBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{
    public function getlastAnnonces($maxAdds = 10){
        
        $qb = $this->createQueryBuilder('a')
            ->orderBy('a.createdAt', 'DESC');
        
            // check validty : select created_at, DATE_ADD(created_at, INTERVAL 2 year) from Annonce ;
            $qb->andWhere("DATE_ADD(a.validatedAt, a.validity, 'DAY') > CURRENT_DATE()");

            // Is valid adds ?
            $qb->andWhere("a.isEnabled = 1");
        
            //$maxAdds = $this->container->getParameter('max_adds_per_page');

            $qb->orderBy('a.createdAt', 'DESC')
                ->setMaxResults($maxAdds);
        $query = $qb->getQuery();
        
        return $query->getResult();
    }
    
    
    public function searchAnnonces( $page=1, $maxperpage=10, $data ){
        
        $qb = $this->createQueryBuilder('a');
             
        $cpt = 1 ;
        foreach ($data as $key => $value) {
            
            if($value === NULL )                continue;
            if($key == "withPhotos")            continue;
            
            // Specific cases
            if(is_object($value)){
                $qb->andWhere('a.'.$key.' = ?'.$cpt);
                $qb->setParameter($cpt, $value->getId());
                $cpt++;
                continue;
            }
            if($key == 'min_price'){
                $qb->andWhere('a.price >= ?'.$cpt);
                $qb->setParameter($cpt, $value);
                $cpt++;
                continue;
            }
            if($key == 'max_price'){
                $qb->andWhere('a.price <= ?'.$cpt);
                $qb->setParameter($cpt, $value);
                $cpt++;
                continue;
            }
            if($key == 'age'){
                $qb->andWhere('a.release > ?'.$cpt);
                $qb->setParameter($cpt, new \DateTime('-'.$value.' year'));
                $cpt++;
                continue;
            }


            
            // default
            $qb->andWhere('a.'.$key.' = ?'.$cpt);
            $qb->setParameter($cpt, $value);



             
             $cpt ++;
        }
        
       
        // check validty : select created_at, DATE_ADD(created_at, INTERVAL 2 year) from Annonce ;
        $qb->andWhere("DATE_ADD(a.validatedAt, a.validity, 'DAY') > CURRENT_DATE()");
        
        
        // Is valid adds ?
        $qb->andWhere("a.isEnabled = 1");      

        $qb->orderBy('a.createdAt', 'DESC');
        
        $qb->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);
        
       //  return $qb->getQuery()->getResult();
        
       return new Paginator($qb);
        
        
    }
    
    
    public function getCountAdds(){
        $qb = $this->createQueryBuilder('a');
        return count($qb->getQuery()->getResult());
    }

    // find adds by user

    public function findAddsByUser($user = null){

        $qb = $this->createQueryBuilder('a');
        
        if( is_object($user)){
            $qb->andWhere('a.user = :USER');
            $qb->setParameter('USER', $user->getId());
        }
        $qb->orderBy('a.createdAt', 'DESC');
        $query = $qb->getQuery();
        
        $results = $query->getResult();
        // set add Status
        foreach ($results as $entity) {
            // annonce valides
            $entity->setStatus(1);         
        }
        
        return $results ;
    }


    

 }
