<?php

namespace Star\AnnoncesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DelegRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DelegRepository extends EntityRepository
{
}
