<?php

namespace Star\AnnoncesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocalityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalityRepository extends EntityRepository
{
}
